---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service-canary
spec:
  ports:
  - nodePort: 8081
    port: 8080
  selector:
    app: train-schedule
    track: canary
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-schedule
  name: train-schedule-deployment-canary
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: train-schedule
      track: canary
  template:
    metadata:
      labels:
        app: train-schedule
        track: canary
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
        name: train-schedule
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
