---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service-canary
spec:
  ports:
  - nodePort: 30001
    port: 9080
  selector:
    app: train-schedule
    track: canary
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train-schedule
  name: train-schedule-deployment-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train-schedule
      track: canary
  template:
    metadata:
      labels:
        app: train-schedule
        track: canary
    spec:
      containers:
      - image: deepakchp/train-schedule
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
        name: train-schedule
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 200m
